import React,{useEffect,useMemo,useState} from 'react';
import {useSelector} from 'react-redux';
import {Navigate} from 'react-router-dom';
import {adminApi} from '../api/adminApi';
import {integrationApi} from '../api/integrationApi';
import Rating from '../components/common/Rating';
import {BarChart3,Boxes,Package,Users,IndianRupee,RefreshCw,Plus,Trash2,CheckCircle2,AlertTriangle} from 'lucide-react';

const blank={name:'',slug:'',description:'',price:'',mrp:'',stock:0,imageUrl:'',categoryId:'',active:true};
export default function AdminDashboard(){
 const user=useSelector(s=>s.auth.user); const [tab,setTab]=useState('overview'); const [data,setData]=useState(null); const [products,setProducts]=useState([]); const [cats,setCats]=useState([]); const [orders,setOrders]=useState([]); const [users,setUsers]=useState([]); const [form,setForm]=useState(blank); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [reviews,setReviews]=useState([]);
 if(!user || !['ADMIN','SELLER'].includes(user.role)) return <Navigate to="/" replace/>;
 const isAdmin=user.role==='ADMIN';
 const load=async()=>{setLoading(true);setError('');try{const [p,c,o]=await Promise.all([adminApi.products(),adminApi.categories(),adminApi.orders()]);setProducts(p.data);setCats(c.data);setOrders(o.data);if(isAdmin){const [d,u,r]=await Promise.all([adminApi.dashboard(),adminApi.users(),adminApi.pendingReviews()]);setData(d.data);setUsers(u.data);setReviews(r.data)}}catch(e){setError(e.response?.data?.message||'Unable to load admin data.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();try{const payload={...form,price:Number(form.price),mrp:form.mrp?Number(form.mrp):null,stock:Number(form.stock),categoryId:Number(form.categoryId)}; if(form.id) await adminApi.updateProduct(form.id,payload); else await adminApi.createProduct(payload);setForm(blank);await load()}catch(e){setError(e.response?.data?.message||'Product save failed.')}};
 const remove=async id=>{if(!confirm('Deactivate this product?'))return;try{await adminApi.deleteProduct(id);await load()}catch(e){setError(e.response?.data?.message||'Delete failed.')}};
 const updateStock=async p=>{const v=prompt('Enter new stock quantity',p.stock);if(v===null)return;try{await adminApi.inventory(p.id,Number(v));await load()}catch(e){setError(e.response?.data?.message||'Inventory update failed.')}};
 const updateStatus=async(o,status)=>{try{await adminApi.updateOrderStatus(o.orderNumber,status);await load()}catch(e){setError(e.response?.data?.message||'Status update failed.')}};
 const tabs=['overview','products','inventory','orders',...(isAdmin?['users','categories','reviews']:[])];
 return <div className="admin-shell"><div className="admin-head"><div><div className="eyebrow">ASTRA CONTROL CENTER</div><h1>Commerce Dashboard</h1><p>Manage catalog, inventory, orders and platform operations.</p></div><button className="secondary-btn" onClick={load}><RefreshCw size={16}/> Refresh</button></div>
 {error&&<div className="error-banner">{error}</div>}
 <div className="admin-tabs">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {loading&&!data&&<div className="empty-card">Loading control center…</div>}
 {tab==='overview'&&<Overview data={data} orders={orders} products={products}/>} 
 {tab==='products'&&<ProductManager products={products} cats={cats} form={form} setForm={setForm} submit={submit} remove={remove}/>} 
 {tab==='inventory'&&<Inventory products={products} updateStock={updateStock}/>} 
 {tab==='orders'&&<OrdersAdmin orders={orders} updateStatus={updateStatus}/>} 
 {tab==='users'&&isAdmin&&<UsersAdmin users={users} reload={load}/>} 
 {tab==='categories'&&isAdmin&&<CategoryManager cats={cats} reload={load}/>} {tab==='reviews'&&isAdmin&&<ReviewModeration reviews={reviews} reload={load}/>} 
 </div>
}
function Overview({data,orders,products}){if(!data)return <div className="empty-card"><BarChart3/> Seller access includes operational tabs; analytics are available to administrators.</div>; const cards=[['Revenue',`₹${Number(data.revenue||0).toLocaleString('en-IN')}`,IndianRupee],['Users',data.users,Users],['Products',data.products,Package],['Low stock',data.lowStockProducts,AlertTriangle],['Orders',data.orders,Boxes],['Pending',data.pendingOrders,BarChart3]];return <><div className="metric-grid">{cards.map(([l,v,I])=><div className="metric-card" key={l}><I size={19}/><span>{l}</span><strong>{v}</strong></div>)}</div><div className="admin-panels"><div className="admin-panel"><h3>Recent orders</h3>{orders.slice(0,8).map(o=><div className="mini-row" key={o.orderNumber}><span><b>{o.orderNumber}</b><small>{o.customerName}</small></span><strong>₹{Number(o.total).toFixed(2)}</strong><em>{o.status}</em></div>)}</div><div className="admin-panel"><h3>Low-stock products</h3>{products.filter(p=>p.active&&p.stock<=10).slice(0,8).map(p=><div className="mini-row" key={p.id}><span><b>{p.name}</b><small>{p.categoryName}</small></span><strong>{p.stock} left</strong></div>)}{products.filter(p=>p.active&&p.stock<=10).length===0&&<p>No low-stock products.</p>}</div></div></>}
function ProductManager({products,cats,form,setForm,submit,remove}){return <div className="admin-panels"><div className="admin-panel form-panel"><h3>{form.id?'Edit product':'Create product'}</h3><form onSubmit={submit} className="admin-form">{[['name','Name'],['slug','Slug'],['price','Price'],['mrp','MRP'],['stock','Stock'],['imageUrl','Image URL']].map(([k,l])=><label key={k}>{l}<input value={form[k]} type={['price','mrp','stock'].includes(k)?'number':'text'} onChange={e=>setForm({...form,[k]:e.target.value})} required={['name','slug','price','stock'].includes(k)}/></label>)}<label>Category<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})} required><option value="">Select</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><button className="primary-btn"><Plus size={16}/>{form.id?'Update':'Create'} product</button>{form.id&&<button type="button" className="secondary-btn" onClick={()=>setForm(blank)}>Cancel</button>}</form></div><div className="admin-panel"><h3>Catalog <span>{products.length}</span></h3><div className="table-wrap"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><div className="table-product"><img src={p.imageUrl}/><span>{p.name}<small>{p.categoryName}</small></span></div></td><td>₹{Number(p.price).toFixed(2)}</td><td>{p.stock}</td><td>{p.active?'Active':'Hidden'}</td><td><button className="icon-btn" onClick={()=>setForm({...p,categoryId:p.categoryId})}>Edit</button><button className="icon-btn danger" onClick={()=>remove(p.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div></div></div>}
function Inventory({products,updateStock}){return <div className="admin-panel"><h3>Inventory control</h3><div className="table-wrap"><table><thead><tr><th>Product</th><th>Stock</th><th>Health</th><th/></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}</td><td><b>{p.stock}</b></td><td><span className={`stock-badge ${p.stock<=10?'low':''}`}>{p.stock<=10?'LOW':'OK'}</span></td><td><button className="icon-btn" onClick={()=>updateStock(p)}>Adjust</button></td></tr>)}</tbody></table></div></div>}
function OrdersAdmin({orders,updateStatus}){const [shipments,setShipments]=useState({}); const create=async no=>{try{const r=await integrationApi.createShipment(no);setShipments(x=>({...x,[no]:r.data}));}catch(e){alert(e.response?.data?.message||'Shipping provider is not configured.')}}; const next={PLACED:'CONFIRMED',CONFIRMED:'PACKED',PACKED:'SHIPPED',SHIPPED:'DELIVERED'};return <div className="admin-panel"><h3>Order operations</h3><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th/></tr></thead><tbody>{orders.map(o=><tr key={o.orderNumber}><td><b>{o.orderNumber}</b><small>{new Date(o.createdAt).toLocaleString()}</small></td><td>{o.customerName}<small>{o.email}</small></td><td>₹{Number(o.total).toFixed(2)}</td><td>{o.paymentStatus}</td><td><span className="status-pill">{o.status}</span></td><td>{next[o.status]&&<button className="icon-btn" onClick={()=>updateStatus(o,next[o.status])}>{next[o.status]}</button>}<button className="icon-btn" onClick={()=>create(o.orderNumber)}>Shiprocket</button>{shipments[o.orderNumber]?.trackingNumber&&<small>{shipments[o.orderNumber].trackingNumber}</small>}</td></tr>)}</tbody></table></div></div>}
function UsersAdmin({users,reload}){const change=async(u,role)=>{try{await adminApi.updateUser(u.id,{role});await reload()}catch{}};return <div className="admin-panel"><h3>User management</h3><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Verified</th><th>Enabled</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b><small>{u.email}</small></td><td><select value={u.role} onChange={e=>change(u,e.target.value)}><option>CUSTOMER</option><option>SELLER</option><option>ADMIN</option></select></td><td>{u.emailVerified?'Yes':'No'}</td><td>{u.enabled?'Yes':'No'}</td><td>{u.role!=='CUSTOMER'&&<CheckCircle2 size={17}/>}</td></tr>)}</tbody></table></div></div>}
function CategoryManager({cats,reload}){const [f,setF]=useState({name:'',slug:'',imageUrl:'',active:true});const save=async e=>{e.preventDefault();try{await adminApi.createCategory(f);setF({name:'',slug:'',imageUrl:'',active:true});reload()}catch{}};return <div className="admin-panel"><h3>Create category</h3><form className="inline-form" onSubmit={save}><input placeholder="Name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><input placeholder="Slug" value={f.slug} onChange={e=>setF({...f,slug:e.target.value})} required/><input placeholder="Image URL" value={f.imageUrl} onChange={e=>setF({...f,imageUrl:e.target.value})}/><button className="primary-btn">Add</button></form><div className="category-admin-grid">{cats.map(c=><div key={c.id}><img src={c.imageUrl}/><b>{c.name}</b><small>{c.slug}</small></div>)}</div></div>}


function ReviewModeration({reviews,reload}){const act=async(id,publish)=>{try{publish?await adminApi.publishReview(id):await adminApi.rejectReview(id);reload()}catch{}};return <div className="admin-panel"><h3>Review moderation <span>{reviews.length} pending</span></h3>{reviews.length===0?<p>No pending reviews.</p>:<div className="review-list">{reviews.map(r=><article className="review-card" key={r.id}><div className="review-head"><strong>{r.reviewerName}</strong><span>{r.productName}</span><span className="review-date">{new Date(r.createdAt).toLocaleString()}</span></div><Rating value={r.rating}/><h3>{r.title}</h3><p>{r.body}</p><div className="detail-actions"><button className="primary-btn" onClick={()=>act(r.id,true)}>Publish</button><button className="secondary-btn" onClick={()=>act(r.id,false)}>Reject</button></div></article>)}</div>}</div>}
