## Production profile
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=false
#logging.level.root=INFO
#logging.level.com.astra=INFO
#spring.cache.type=redis
#management.endpoint.health.show-details=never
#spring.rabbitmq.listener.simple.auto-startup=false
#
#astra.rabbit.enabled=${RABBITMQ_ENABLED:false}


# straing point
# -Dspring.profiles.active=prod

spring.datasource.url=jdbc:postgresql://localhost:5432/astra_prod
spring.datasource.username=postgres
spring.datasource.password=Postgres@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.cache.type=redis

logging.level.root=INFO
logging.level.com.astra=INFO

management.endpoint.health.show-details=never

spring.rabbitmq.listener.simple.auto-startup=false
astra.rabbit.enabled=${RABBITMQ_ENABLED:false}
