spring.application.name=astra_server


# =========================================================
# ASTRA LOCAL PROFILE
# =========================================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/astra_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true}

spring.datasource.username=${DB_USERNAME:root}

spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

logging.level.com.astra=DEBUG

astra.cors.allowed-origins=http://localhost:5173

astra.app.environment=local


spring.rabbitmq.listener.simple.auto-startup=false
management.health.rabbit.enabled=false
astra.rabbit.enabled=false

